/**
 * M06 Synthesis Engine — SynthesisService
 *
 * Transforms a structured AssembledPackage (from M05) into a concise
 * natural-language narrative via an LLM call. The narrative is returned
 * to the M08 Context Sidecar and included in the SidecarContextPackage.
 *
 * Caching: synthesis results are cached per (entityId, assembledAt) for 90 s.
 * Cache is invalidated when a new signal arrives for the entity (same
 * invalidate() call pattern as M05).
 *
 * The synthesis service is optional — callers (M08 SidecarService) pass null
 * when the module is disabled and skip synthesis rather than failing.
 */

import type { Result } from '../core/types.js';
import { ok, err } from '../core/types.js';
import { ModuleDisabledError } from '../core/errors.js';
import type { ICache } from '../ports/ICache.js';
import type { AssembledPackage } from '../m05-context-assembler/ContextAssemblerService.js';
import { PromptBuilder } from './PromptBuilder.js';

// ── Internal LLM adapter contract ─────────────────────────────────────────────
//
// SynthesisService uses its own narrower adapter interface rather than the
// ILanguageModel port so it can pass a systemPrompt directly and receive
// a `content` field without coupling to the outer port's field names.
// The AnthropicAdapter and StubLanguageModel implement both interfaces.

export interface SynthesisLlmRequest {
  systemPrompt: string;
  messages:     Array<{ role: 'user' | 'assistant'; content: string }>;
  maxTokens:    number;
  temperature:  number;
}

export interface SynthesisLlmResponse {
  content:      string;
  inputTokens:  number;
  outputTokens: number;
  modelUsed:    string;
}

export interface ISynthesisLlm {
  complete(request: SynthesisLlmRequest): Promise<SynthesisLlmResponse>;
  defaultModel(): string;
  close(): Promise<void>;
}

// ── Output types ──────────────────────────────────────────────────────────────

export interface SynthesisResult {
  entityId:          string;
  requestingAgentId: string;
  /** Free-text narrative generated by the LLM. */
  narrative:         string;
  /** Model identifier that produced this narrative. */
  modelUsed:         string;
  inputTokens:       number;
  outputTokens:      number;
  /** Wall-clock milliseconds the LLM call took (0 on a cache hit). */
  synthesisMs:       number;
  cacheHit:          boolean;
  synthesisedAt:     Date;
}

// ── Service ──────────────────────────────────────────────────────────────────

export class SynthesisService {
  private readonly CACHE_TTL    = 90;   // seconds
  private readonly CACHE_PREFIX = 'cf:synthesis:';
  private readonly MAX_TOKENS   = 600;
  private readonly TEMPERATURE  = 0.1;

  constructor(
    private readonly llm:     ISynthesisLlm,
    private readonly cache:   ICache,
    private readonly enabled: boolean,
    private readonly builder: PromptBuilder = new PromptBuilder(),
  ) {}

  // ── Synthesise ────────────────────────────────────────────────────────────

  async synthesise(pkg: AssembledPackage): Promise<Result<SynthesisResult>> {
    if (!this.enabled) return err(new ModuleDisabledError('M06_SYNTHESIS_ENGINE'));

    const cacheKey = this._cacheKey(pkg);
    const cached   = await this.cache.get(cacheKey);

    if (cached) {
      const raw = JSON.parse(cached) as SynthesisResult;
      return ok({
        ...raw,
        synthesisedAt: new Date(raw.synthesisedAt),
        cacheHit:      true,
      });
    }

    // Determine requesting agent's domain from the assembled package
    const topDomain =
      (pkg.signals[0]?.sourceDomain) ??
      'SHARED';

    const systemPrompt = this.builder.buildSystemPrompt(
      pkg.requestingAgentId,
      topDomain as Parameters<PromptBuilder['buildSystemPrompt']>[1],
    );
    const userContent = this.builder.buildUserPrompt(pkg);

    const startMs = Date.now();
    const llmResp = await this.llm.complete({
      systemPrompt,
      messages:    [{ role: 'user', content: userContent }],
      maxTokens:   this.MAX_TOKENS,
      temperature: this.TEMPERATURE,
    });
    const synthesisMs = Date.now() - startMs;

    const result: SynthesisResult = {
      entityId:          pkg.entityId,
      requestingAgentId: pkg.requestingAgentId,
      narrative:         llmResp.content,
      modelUsed:         llmResp.modelUsed,
      inputTokens:       llmResp.inputTokens,
      outputTokens:      llmResp.outputTokens,
      synthesisMs,
      cacheHit:          false,
      synthesisedAt:     new Date(),
    };

    await this.cache.set(cacheKey, JSON.stringify(result), this.CACHE_TTL);
    return ok(result);
  }

  /**
   * Invalidate synthesis cache for an entity.
   * Called when a new signal arrives for the entity (M04 subscription).
   */
  async invalidate(entityId: string): Promise<void> {
    await this.cache.flushPrefix(`${this.CACHE_PREFIX}${entityId}:`);
  }

  // ── Private helpers ───────────────────────────────────────────────────────

  private _cacheKey(pkg: AssembledPackage): string {
    const assembledTs = pkg.assembledAt instanceof Date
      ? pkg.assembledAt.toISOString()
      : String(pkg.assembledAt);
    return `${this.CACHE_PREFIX}${pkg.entityId}:${pkg.requestingAgentId}:${assembledTs}`;
  }
}
