/**
 * M03 Context Store — Drizzle Schema
 *
 * The Context Store builds a queryable view over the append-only signal log.
 *
 * cf_inferences  : Reasoned inferences generated by the Inference Engine (M07).
 *                  Stored separately from raw signals for different retention rules.
 * cf_decisions   : Actions taken by agents (7-year regulatory retention, FCA/PRA).
 * cf_context_snapshots : Frozen context taken at workflow start (WorkflowOrchestrator).
 *
 * Note: cf_signals (the raw signal log) is defined in M01's schema.
 *       This module adds the inference and decision layers on top.
 */

import {
  pgTable,
  text,
  real,
  boolean,
  timestamp,
  index,
} from 'drizzle-orm/pg-core';

/**
 * Inferences derived from signal patterns.
 * Written by the Inference Engine (M07) — Phase 2.
 * Readable by M03 for context assembly.
 *
 * Inferences have GDPR expiry: 90 days unless connected to an active case.
 */
export const cfInferences = pgTable(
  'cf_inferences',
  {
    inferenceId:   text('inference_id').primaryKey(),
    entityId:      text('entity_id').notNull(),
    inferenceType: text('inference_type').notNull(),   // e.g. "financial_difficulty", "vulnerability"
    summary:       text('summary').notNull(),
    confidence:    real('confidence').notNull(),
    evidenceJson:  text('evidence_json').notNull(),    // JSON array of signalIds that drove this
    domain:        text('domain').notNull(),
    isActive:      boolean('is_active').notNull().default(true),
    isRedacted:    boolean('is_redacted').notNull().default(false),
    derivedAt:     timestamp('derived_at',  { withTimezone: true }).notNull(),
    expiresAt:     timestamp('expires_at',  { withTimezone: true }),
    createdAt:     timestamp('created_at',  { withTimezone: true }).notNull().defaultNow(),
  },
  t => ({
    entityIdx:       index('idx_cf_inferences_entity').on(t.entityId),
    domainIdx:       index('idx_cf_inferences_domain').on(t.domain, t.inferenceType),
    activeEntityIdx: index('idx_cf_inferences_active').on(t.entityId, t.isActive),
    expiresAtIdx:    index('idx_cf_inferences_expires').on(t.expiresAt),
  }),
);

/**
 * Regulatory decisions taken by agents.
 * Retained for 7 years (FCA/PRA requirement).
 * Entity linkage is redacted on DSAR, but the decision record is preserved.
 */
export const cfDecisions = pgTable(
  'cf_decisions',
  {
    decisionId:    text('decision_id').primaryKey(),
    entityId:      text('entity_id'),          // nullable post-DSAR redaction
    sourceAgentId: text('source_agent_id').notNull(),
    domain:        text('domain').notNull(),
    decisionType:  text('decision_type').notNull(), // e.g. "hardship_arrangement", "fraud_block"
    outcome:       text('outcome').notNull(),        // e.g. "APPROVED", "DECLINED", "ESCALATED"
    rationale:     text('rationale').notNull(),
    evidenceJson:  text('evidence_json').notNull(),  // signalIds and inferenceIds used
    contractId:    text('contract_id').notNull(),
    correlationId: text('correlation_id'),
    sessionId:     text('session_id'),
    isRedacted:    boolean('is_redacted').notNull().default(false),
    decidedAt:     timestamp('decided_at',  { withTimezone: true }).notNull(),
    expiresAt:     timestamp('expires_at',  { withTimezone: true }), // 7 years from decidedAt
    createdAt:     timestamp('created_at',  { withTimezone: true }).notNull().defaultNow(),
  },
  t => ({
    entityIdx:     index('idx_cf_decisions_entity').on(t.entityId),
    agentIdx:      index('idx_cf_decisions_agent').on(t.sourceAgentId),
    domainIdx:     index('idx_cf_decisions_domain').on(t.domain),
    sessionIdx:    index('idx_cf_decisions_session').on(t.sessionId),
  }),
);

/**
 * Frozen context snapshots taken by WorkflowOrchestrators at trigger time.
 * The workflow runs against this snapshot; it is not updated mid-run.
 * Only IMMEDIATE signals can amend a snapshot in-flight (via CriticalInterrupt).
 */
export const cfContextSnapshots = pgTable(
  'cf_context_snapshots',
  {
    snapshotId:   text('snapshot_id').primaryKey(),
    entityId:     text('entity_id').notNull(),
    workflowId:   text('workflow_id').notNull(),
    orchestratorId: text('orchestrator_id').notNull(),
    contextJson:  text('context_json').notNull(),  // full assembled context at snapshot time
    snapshotAt:   timestamp('snapshot_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt:    timestamp('expires_at',  { withTimezone: true }),
  },
  t => ({
    entityIdx:    index('idx_cf_snapshots_entity').on(t.entityId),
    workflowIdx:  index('idx_cf_snapshots_workflow').on(t.workflowId),
  }),
);

export type DbInference       = typeof cfInferences.$inferSelect;
export type NewInference      = typeof cfInferences.$inferInsert;
export type DbDecision        = typeof cfDecisions.$inferSelect;
export type NewDecision       = typeof cfDecisions.$inferInsert;
export type DbContextSnapshot = typeof cfContextSnapshots.$inferSelect;
export type NewContextSnapshot = typeof cfContextSnapshots.$inferInsert;
